version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '12:00'
    labels:
      - 'Meta: Dependencies'
      - 'Meta: Github'
