pull_request_rules:
  - name: Automatic Depfu merging
    conditions:
      - author=depfu[bot]
      - base=staging
      - label~=^Meta:\ Dependencies
    actions:
      merge:
        method: squash
  - name: Automatic Dependabot merging
    conditions:
      - author=dependabot[bot]
      - base=master
      - label~=^Meta:\ Dependencies
    actions:
      merge:
        method: squash
  - name: Automatic Updater Merging
    conditions:
      - approved-reviews-by=Favna
      - base=staging
      - author=Favware-bot
      - label~=^Meta:\ Data\ Update
    actions:
      merge:
        method: squash
