/**
 * Array of species names that are not present in Generation 8 or 9.
 */
export const speciesThatAreNotInGeneration8Nor9: string[] = [
  'snivy',
  'servine',
  'serperior',
  'tepig',
  'pignite',
  'emboar',
  'patrat',
  'watchog',
  'pansage',
  'simisage',
  'pansear',
  'simisear',
  'panpour',
  'simipour',
  'blitzle',
  'zebstrika',
  'sewaddle',
  'swadloon',
  'leavanny',
  'ducklett',
  'swanna',
  'furfrou',
  'pikipek',
  'trumbeak',
  'toucannon',
  'minior'
];
