version: '2.4'
services:
  pokedex:
    build: ./
    container_name: graphql-pokemon
    image: 'favware/graphql-pokemon:latest'
    networks:
      - pokedex
    ports:
      - '8080:4000'
    restart: 'no'

networks:
  pokedex:
