export function getTextContent(bit1: string) {
  return bit1
    ?.split(/\|[a-z]+=/g)
    ?.at(-1)
    .replace(/}}$/, '')
    .replace(/<sc>([a-zA-Z {}|]+)<\/sc>/, '')
    .replace(/{{[pP]\|([a-zA-Z']+)}}/g, '$1')
    .replace(/{{[pP]\|[a-zA-Z']+\|([a-zA-Z'é ]+)}}/g, '$1')
    .replace(/{{p\|[a-zA-Z]+\|(evolve)}}/g, '$1')
    .replace(/{{m\|([a-zA-Z ]+)}}/g, '$1')
    .replace(/{{m\|[a-zA-Z ]+\|([a-zA-Z -]+)}}/g, '$1')
    .replace(/{{t\|([a-zA-Z]+)}}/g, '$1')
    .replace(/{{tt\|([-a-zA-Z0-9,.\/()&;–−'"° ]+)\|[-a-zA-Z0-9,.\/()&;–−'"° ]+}}/g, '$1')
    .replace(/{{a\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replace(/{{a\|[-a-zA-Z0-9, ]+\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replace(/{{status\|[-a-zA-Z0-9,.\/ ]+\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replace(/{{status\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replace(/{{pkmn\|([a-zA-Z]+)}}/g, '$1')
    .replace(/{{pkmn2\|([a-zA-Z]+)}}/g, '$1')
    .replace(/{{wp\|([a-zA-Z ]+)}}/g, '$1')
    .replace(/{{wp\|[a-zA-Z ()]+\|([a-zA-Z. ]+)}}/g, '$1')
    .replaceAll('{{tt|*|Pokédex entry only found in Pokémon HOME.}}', '')
    .replaceAll('{{tt|*|Pokédex entry only found in Pokémon HOME}}', '')
    .replaceAll('{{tt|*|In Ver 1.0, Tyranitar uses its entry from LeafGreen}}', '')
    .replaceAll('’', "'")
    .replaceAll('−', '-')
    .replaceAll('“', '"')
    .replaceAll('”', '"')
    .replaceAll(' <!--error in game--> ', ' ')
    .replaceAll('<!-- period is missing -->', '.')
    .replaceAll(`{{tt|–75<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−60 degrees Celsius}}`, '-75 degrees Fahrenheit')
    .replaceAll(`{{tt|–75<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-60 degrees Celsius}}`, '-75 degrees Fahrenheit')
    .replaceAll(`{{tt|–58<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−50 degrees Celsius}}`, '-58 degrees Fahrenheit')
    .replaceAll(`{{tt|–58<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-50 degrees Celsius}}`, '-58 degrees Fahrenheit')
    .replaceAll(`{{tt|–240<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−150 degrees Celsius}}`, '-240 degrees Fahrenheit')
    .replaceAll(`{{tt|–240<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-150 degrees Celsius}}`, '-240 degrees Fahrenheit')
    .replaceAll(`{{tt|this|''the'' in Ruby v1.0}}`, 'this')
    .replaceAll(`{{tt|Bug/Grass Pokémon|''BUG POKéMON'' in R/S v1.0}}`, 'Bug/Grass Pokémon')
    .replaceAll('{{tt|*|Unused entry}}', '')
    .replaceAll('[[evolution]]', 'evolution')
    .replaceAll('[[Evolution|evolve]]', 'evolve')
    .replaceAll('[[Moon Stone|moon stone]]', 'moon stone')
    .replaceAll('[[regional form]]', 'regional form')
    .replaceAll('[[Pokégear]]', 'Pokégear')
    .replaceAll('[[alien]]', 'alien')
    .replaceAll('[[Double Slap (move)|DoubleSlap]]', 'DoubleSlap')
    .replaceAll('[[Old Amber|amber]]', 'amber')
    .replaceAll('[[Mr. Fuji|a certain scientist]]', 'a certain scientist')
    .replaceAll('[[move]]', 'move')
    .replaceAll('[[Berry|Berries]]', 'Berries')
    .replaceAll('[[Evolution|becomes]]', 'becomes')
    .replaceAll('[[Pupitar (Pokémon)|a pupa]]', 'a pupa')
    .replaceAll('[[Poké Ball]]', 'Poké Ball')
    .replaceAll('[[Gladion|the boy who evolved it into this form]]', 'the boy who evolved it into this form')
    .replaceAll('[[Ultra Beast]]', 'Ultra Beast')
    .replaceAll('[[Dynamax]]', 'Dynamax')
    .replaceAll('[[region]]', 'region')
    .replaceAll('[[Alola]]', 'Alola')
    .replaceAll('[[Hisui]]', 'Hisui')
    .replaceAll('[[Galar]]', 'Galar')
    .replaceAll('[[Paldea]]', 'Paldea')
    .replaceAll('[[Kitakami|a new land]]', 'a new land')
    .replaceAll('[[Scarlet Book|an expedition journal]]', 'an expedition journal')
    .replaceAll('[[Mega Evolution|a phenomenon that occurs in a certain region]]', 'a phenomenon that occurs in a certain region')
    .replaceAll('[[Violet Book|certain expedition journal.]]', 'certain expedition journal.')
    .replaceAll('[[Scarlet Book|old expedition journal]]', 'old expedition journal.')
    .replaceAll('[[Violet Book|old book]]', 'old book.');
}
