import { Pokedex } from '#dexdata/pokedex';
import type { PokemonTypes } from '#utils/pokemon';

const entries: [string, PokemonTypes.DexEntry][] = [
  [
    'rowlet',
    {
      abilities: { first: 'Overgrow', hidden: 'Long Reach' },
      baseStats: { hp: 68, atk: 55, def: 55, spa: 50, spd: 50, spe: 42 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Brown',
      eggGroups: ['Flying'],
      evYields: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['dartrix'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 722,
      species: 'rowlet',
      types: ['Grass', 'Flying'],
      weightkg: 1.5,
      aliases: ['mokuroo']
    }
  ],
  [
    'dartrix',
    {
      abilities: { first: 'Overgrow', hidden: 'Long Reach' },
      baseStats: { hp: 78, atk: 75, def: 75, spa: 70, spd: 70, spe: 52 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Brown',
      eggGroups: ['Flying'],
      evYields: { hp: 2, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 17,
      evos: ['decidueye'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.7,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 723,
      prevo: 'rowlet',
      species: 'dartrix',
      types: ['Grass', 'Flying'],
      weightkg: 16,
      aliases: ['fukusuroo']
    }
  ],
  [
    'decidueye',
    {
      abilities: { first: 'Overgrow', hidden: 'Long Reach' },
      baseStats: { hp: 78, atk: 107, def: 75, spa: 100, spd: 100, spe: 70 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Brown',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 34,
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 1.6,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 724,
      prevo: 'dartrix',
      species: 'decidueye',
      types: ['Grass', 'Ghost'],
      weightkg: 36.6,
      aliases: ['junaipaa']
    }
  ],
  [
    'litten',
    {
      abilities: { first: 'Blaze', hidden: 'Intimidate' },
      baseStats: { hp: 45, atk: 65, def: 40, spa: 60, spd: 40, spe: 70 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Red',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 1 },
      evos: ['torracat'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 725,
      species: 'litten',
      types: ['Fire'],
      weightkg: 4.3,
      aliases: ['nyabii']
    }
  ],
  [
    'torracat',
    {
      abilities: { first: 'Blaze', hidden: 'Intimidate' },
      baseStats: { hp: 65, atk: 85, def: 50, spa: 80, spd: 50, spe: 90 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Red',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      evoLevel: 17,
      evos: ['incineroar'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.7,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 726,
      prevo: 'litten',
      species: 'torracat',
      types: ['Fire'],
      weightkg: 25,
      aliases: ['nyahiito']
    }
  ],
  [
    'incineroar',
    {
      abilities: { first: 'Blaze', hidden: 'Intimidate' },
      baseStats: { hp: 95, atk: 115, def: 90, spa: 80, spd: 90, spe: 60 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Red',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 34,
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 1.8,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 727,
      prevo: 'torracat',
      species: 'incineroar',
      types: ['Fire', 'Dark'],
      weightkg: 83,
      aliases: ['gaogaen']
    }
  ],
  [
    'popplio',
    {
      abilities: { first: 'Torrent', hidden: 'Liquid Voice' },
      baseStats: { hp: 50, atk: 54, def: 54, spa: 66, spd: 56, spe: 40 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Water 1', 'Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 1, spd: 0, spe: 0 },
      evos: ['brionne'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 728,
      species: 'popplio',
      types: ['Water'],
      weightkg: 7.5,
      aliases: ['ashimari']
    }
  ],
  [
    'brionne',
    {
      abilities: { first: 'Torrent', hidden: 'Liquid Voice' },
      baseStats: { hp: 60, atk: 69, def: 69, spa: 91, spd: 81, spe: 50 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Water 1', 'Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      evoLevel: 17,
      evos: ['primarina'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 729,
      prevo: 'popplio',
      species: 'brionne',
      types: ['Water'],
      weightkg: 17.5,
      aliases: ['oshamari']
    }
  ],
  [
    'primarina',
    {
      abilities: { first: 'Torrent', hidden: 'Liquid Voice' },
      baseStats: { hp: 80, atk: 74, def: 74, spa: 126, spd: 116, spe: 60 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Water 1', 'Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      evoLevel: 34,
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 1.8,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 3855,
      num: 730,
      prevo: 'brionne',
      species: 'primarina',
      types: ['Water', 'Fairy'],
      weightkg: 44,
      aliases: ['ashireenu']
    }
  ],
  [
    'pikipek',
    {
      abilities: { first: 'Keen Eye', second: 'Skill Link', hidden: 'Pickup' },
      baseStats: { hp: 35, atk: 75, def: 30, spa: 30, spd: 30, spe: 65 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Black',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['trumbeak'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 731,
      species: 'pikipek',
      types: ['Normal', 'Flying'],
      weightkg: 1.2,
      aliases: ['tsutsukera']
    }
  ],
  [
    'trumbeak',
    {
      abilities: { first: 'Keen Eye', second: 'Skill Link', hidden: 'Pickup' },
      baseStats: { hp: 55, atk: 85, def: 50, spa: 40, spd: 50, spe: 75 },
      catchRate: {
        base: 120,
        percentageWithOrdinaryPokeballAtFullHealth: '24.9%'
      },
      color: 'Black',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 14,
      evos: ['toucannon'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 732,
      prevo: 'pikipek',
      species: 'trumbeak',
      types: ['Normal', 'Flying'],
      weightkg: 14.8,
      aliases: ['kerarappa']
    }
  ],
  [
    'toucannon',
    {
      abilities: {
        first: 'Keen Eye',
        second: 'Skill Link',
        hidden: 'Sheer Force'
      },
      baseStats: { hp: 80, atk: 120, def: 75, spa: 75, spd: 75, spe: 60 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Black',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 28,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 733,
      prevo: 'trumbeak',
      species: 'toucannon',
      types: ['Normal', 'Flying'],
      weightkg: 26,
      aliases: ['dodekabashi']
    }
  ],
  [
    'yungoos',
    {
      abilities: {
        first: 'Stakeout',
        second: 'Strong Jaw',
        hidden: 'Adaptability'
      },
      baseStats: { hp: 48, atk: 70, def: 30, spa: 30, spd: 30, spe: 45 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['gumshoos'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 734,
      species: 'yungoos',
      types: ['Normal'],
      weightkg: 6,
      aliases: ['yanguusu']
    }
  ],
  [
    'gumshoos',
    {
      abilities: {
        first: 'Stakeout',
        second: 'Strong Jaw',
        hidden: 'Adaptability'
      },
      baseStats: { hp: 88, atk: 110, def: 60, spa: 55, spd: 60, spe: 45 },
      catchRate: { base: 127, percentageWithOrdinaryPokeballAtFullHealth: '26%' },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 20,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.7,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 735,
      otherFormes: ['gumshoostotem'],
      prevo: 'yungoos',
      species: 'gumshoos',
      types: ['Normal'],
      weightkg: 14.2,
      aliases: ['dekaguusu']
    }
  ],
  [
    'gumshoostotem',
    {
      abilities: { first: 'Adaptability' },
      baseSpecies: 'Gumshoos',
      baseStats: { hp: 88, atk: 110, def: 60, spa: 55, spd: 60, spe: 45 },
      catchRate: { base: 127, percentageWithOrdinaryPokeballAtFullHealth: '26%' },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 735,
      species: 'gumshoos-totem',
      types: ['Normal'],
      weightkg: 60,
      aliases: ['gumshoost', 'totemgumshoos']
    }
  ],
  [
    'grubbin',
    {
      abilities: { first: 'Swarm' },
      baseStats: { hp: 47, atk: 62, def: 45, spa: 55, spd: 45, spe: 46 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Gray',
      eggGroups: ['Bug'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['charjabug'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 736,
      species: 'grubbin',
      types: ['Bug'],
      weightkg: 4.4,
      aliases: ['agojimushi']
    }
  ],
  [
    'charjabug',
    {
      abilities: { first: 'Battery' },
      baseStats: { hp: 57, atk: 82, def: 95, spa: 55, spd: 75, spe: 36 },
      catchRate: {
        base: 120,
        percentageWithOrdinaryPokeballAtFullHealth: '24.9%'
      },
      color: 'Green',
      eggGroups: ['Bug'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      evoLevel: 20,
      evos: ['vikavolt'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 737,
      prevo: 'grubbin',
      species: 'charjabug',
      types: ['Bug', 'Electric'],
      weightkg: 10.5,
      aliases: ['denjimushi']
    }
  ],
  [
    'vikavolt',
    {
      abilities: { first: 'Levitate' },
      baseStats: { hp: 77, atk: 70, def: 90, spa: 145, spd: 75, spe: 43 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Bug'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      evoLevel: 'Use Thunder Stone',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 738,
      otherFormes: ['vikavolttotem'],
      prevo: 'charjabug',
      species: 'vikavolt',
      types: ['Bug', 'Electric'],
      weightkg: 45,
      aliases: ['kuwaganon']
    }
  ],
  [
    'vikavolttotem',
    {
      abilities: { first: 'Levitate' },
      baseSpecies: 'Vikavolt',
      baseStats: { hp: 77, atk: 70, def: 90, spa: 145, spd: 75, spe: 43 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Bug'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 738,
      species: 'vikavolt-totem',
      types: ['Bug', 'Electric'],
      weightkg: 147.5,
      aliases: ['totemvikavolt', 'vikavoltt']
    }
  ],
  [
    'crabrawler',
    {
      abilities: {
        first: 'Hyper Cutter',
        second: 'Iron Fist',
        hidden: 'Anger Point'
      },
      baseStats: { hp: 47, atk: 82, def: 57, spa: 42, spd: 47, spe: 63 },
      catchRate: {
        base: 225,
        percentageWithOrdinaryPokeballAtFullHealth: '39.9%'
      },
      color: 'Purple',
      eggGroups: ['Water 3'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['crabominable'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 739,
      species: 'crabrawler',
      types: ['Fighting'],
      weightkg: 7,
      aliases: ['makenkani']
    }
  ],
  [
    'crabominable',
    {
      abilities: {
        first: 'Hyper Cutter',
        second: 'Iron Fist',
        hidden: 'Anger Point'
      },
      baseStats: { hp: 97, atk: 132, def: 77, spa: 62, spd: 67, spe: 43 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'White',
      eggGroups: ['Water 3'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'Level up in extreme cold',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.7,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 740,
      prevo: 'crabrawler',
      species: 'crabominable',
      types: ['Fighting', 'Ice'],
      weightkg: 180,
      aliases: ['kekenkani']
    }
  ],
  [
    'oricorio',
    {
      abilities: { first: 'Dancer' },
      baseForme: 'Baile',
      baseStats: { hp: 75, atk: 70, def: 70, spa: 98, spd: 70, spe: 93 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Red',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      genderRatio: { male: '25%', female: '75%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 741,
      otherFormes: ['oricoriopompom', 'oricoriopau', 'oricoriosensu'],
      species: 'oricorio',
      types: ['Fire', 'Flying'],
      weightkg: 3.4,
      aliases: ['odoridori', 'oricoriob', 'oricoriobaile', 'oricoriof', 'oricoriofire']
    }
  ],
  [
    'oricoriopompom',
    {
      abilities: { first: 'Dancer' },
      baseSpecies: 'Oricorio',
      baseStats: { hp: 75, atk: 70, def: 70, spa: 98, spd: 70, spe: 93 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Yellow',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      forme: 'Pom-Pom',
      formeLetter: 'P',
      genderRatio: { male: '25%', female: '75%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 741,
      species: 'oricorio-pom-pom',
      types: ['Electric', 'Flying'],
      weightkg: 3.4,
      aliases: ['oricorioe', 'oricorioelectric']
    }
  ],
  [
    'oricoriopau',
    {
      abilities: { first: 'Dancer' },
      baseSpecies: 'Oricorio',
      baseStats: { hp: 75, atk: 70, def: 70, spa: 98, spd: 70, spe: 93 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Pink',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      forme: "Pa'u",
      formeLetter: 'P',
      genderRatio: { male: '25%', female: '75%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 741,
      specialBackSprite: 'https://play.pokemonshowdown.com/sprites/ani-back/oricorio-pau.gif',
      specialShinyBackSprite: 'https://play.pokemonshowdown.com/sprites/ani-back-shiny/oricorio-pau.gif',
      specialShinySprite: 'https://play.pokemonshowdown.com/sprites/ani-shiny/oricorio-pau.gif',
      specialSprite: 'https://play.pokemonshowdown.com/sprites/ani/oricorio-pau.gif',
      species: "oricorio-pa'u",
      types: ['Psychic', 'Flying'],
      weightkg: 3.4,
      aliases: ['oricoriop', 'oricoriopsychic']
    }
  ],
  [
    'oricoriosensu',
    {
      abilities: { first: 'Dancer' },
      baseSpecies: 'Oricorio',
      baseStats: { hp: 75, atk: 70, def: 70, spa: 98, spd: 70, spe: 93 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Purple',
      eggGroups: ['Flying'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      forme: 'Sensu',
      formeLetter: 'S',
      genderRatio: { male: '25%', female: '75%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 741,
      species: 'oricorio-sensu',
      types: ['Ghost', 'Flying'],
      weightkg: 3.4,
      aliases: ['oricoriog', 'oricorioghost', 'oricorios']
    }
  ],
  [
    'cutiefly',
    {
      abilities: {
        first: 'Honey Gather',
        second: 'Shield Dust',
        hidden: 'Sweet Veil'
      },
      baseStats: { hp: 40, atk: 45, def: 40, spa: 55, spd: 40, spe: 84 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Yellow',
      eggGroups: ['Bug', 'Fairy'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 1 },
      evos: ['ribombee'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 742,
      species: 'cutiefly',
      types: ['Bug', 'Fairy'],
      weightkg: 0.2,
      aliases: ['aburii']
    }
  ],
  [
    'ribombee',
    {
      abilities: {
        first: 'Honey Gather',
        second: 'Shield Dust',
        hidden: 'Sweet Veil'
      },
      baseStats: { hp: 60, atk: 55, def: 60, spa: 95, spd: 70, spe: 124 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Yellow',
      eggGroups: ['Bug', 'Fairy'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      evoLevel: 25,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 743,
      otherFormes: ['ribombeetotem'],
      prevo: 'cutiefly',
      species: 'ribombee',
      types: ['Bug', 'Fairy'],
      weightkg: 0.5,
      aliases: ['aburibon']
    }
  ],
  [
    'ribombeetotem',
    {
      abilities: { first: 'Sweet Veil' },
      baseSpecies: 'Ribombee',
      baseStats: { hp: 60, atk: 55, def: 60, spa: 95, spd: 70, spe: 124 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Yellow',
      eggGroups: ['Bug', 'Fairy'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 743,
      species: 'ribombee-totem',
      types: ['Bug', 'Fairy'],
      weightkg: 2,
      aliases: ['ribombeet', 'totemribombee']
    }
  ],
  [
    'rockruff',
    {
      abilities: {
        first: 'Keen Eye',
        second: 'Vital Spirit',
        hidden: 'Steadfast',
        special: 'Own Tempo'
      },
      baseForme: 'Midday',
      baseStats: { hp: 45, atk: 65, def: 40, spa: 30, spd: 40, spe: 60 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['lycanroc', 'lycanrocmidnight', 'lycanrocdusk'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 744,
      species: 'rockruff',
      types: ['Rock'],
      weightkg: 9.2,
      aliases: ['iwanko', 'rockruffdusk']
    }
  ],
  [
    'lycanroc',
    {
      abilities: { first: 'Keen Eye', second: 'Sand Rush', hidden: 'Steadfast' },
      baseForme: 'Midday',
      baseStats: { hp: 75, atk: 115, def: 65, spa: 55, spd: 65, spe: 112 },
      catchRate: { base: 90, percentageWithOrdinaryPokeballAtFullHealth: '20.1%' },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'Level 25 during Daytime',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.8,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 745,
      otherFormes: ['lycanrocmidnight', 'lycanrocdusk'],
      prevo: 'rockruff',
      species: 'lycanroc',
      types: ['Rock'],
      weightkg: 25,
      aliases: ['lycanrocday', 'lycanrocmidday', 'rugarugan']
    }
  ],
  [
    'lycanrocmidnight',
    {
      abilities: { first: 'Keen Eye', second: 'Vital Spirit', hidden: 'No Guard' },
      baseSpecies: 'Lycanroc',
      baseStats: { hp: 85, atk: 115, def: 75, spa: 55, spd: 75, spe: 82 },
      catchRate: { base: 90, percentageWithOrdinaryPokeballAtFullHealth: '20.1%' },
      color: 'Red',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'Level 25 during Nightttime',
      forme: 'Midnight',
      formeLetter: 'M',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 745,
      prevo: 'rockruff',
      species: 'lycanroc-midnight',
      types: ['Rock'],
      weightkg: 25,
      aliases: ['lycanrocn', 'lycanrocnight']
    }
  ],
  [
    'lycanrocdusk',
    {
      abilities: { first: 'Tough Claws' },
      baseSpecies: 'Lycanroc',
      baseStats: { hp: 75, atk: 117, def: 65, spa: 55, spd: 65, spe: 110 },
      catchRate: { base: 90, percentageWithOrdinaryPokeballAtFullHealth: '20.1%' },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'from a special Rockruff',
      forme: 'Dusk',
      formeLetter: 'D',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.8,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 745,
      prevo: 'rockruff',
      species: 'lycanroc-dusk',
      types: ['Rock'],
      weightkg: 25,
      aliases: ['lycanrocd']
    }
  ],
  [
    'wishiwashi',
    {
      abilities: { first: 'Schooling' },
      baseForme: 'Solo',
      baseStats: { hp: 45, atk: 20, def: 20, spa: 25, spd: 25, spe: 40 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Blue',
      eggGroups: ['Water 2'],
      evYields: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.2,
      isEggObtainable: true,
      levellingRate: 'Fast',
      minimumHatchTime: 3855,
      num: 746,
      otherFormes: ['wishiwashischool'],
      species: 'wishiwashi',
      types: ['Water'],
      weightkg: 0.3,
      aliases: ['wishiwashisolo', 'yowashi']
    }
  ],
  [
    'wishiwashischool',
    {
      abilities: { first: 'Schooling' },
      baseSpecies: 'Wishiwashi',
      baseStats: { hp: 45, atk: 140, def: 130, spa: 140, spd: 135, spe: 30 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Blue',
      eggGroups: ['Water 2'],
      evYields: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'School',
      formeLetter: 'S',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 8.2,
      isEggObtainable: true,
      levellingRate: 'Fast',
      minimumHatchTime: 3855,
      num: 746,
      species: 'wishiwashi-school',
      types: ['Water'],
      weightkg: 78.6
    }
  ],
  [
    'mareanie',
    {
      abilities: { first: 'Merciless', second: 'Limber', hidden: 'Regenerator' },
      baseStats: { hp: 50, atk: 53, def: 62, spa: 43, spd: 52, spe: 45 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Blue',
      eggGroups: ['Water 1'],
      evYields: { hp: 0, atk: 0, def: 1, spa: 0, spd: 0, spe: 0 },
      evos: ['toxapex'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 747,
      species: 'mareanie',
      types: ['Poison', 'Water'],
      weightkg: 8,
      aliases: ['hidoide']
    }
  ],
  [
    'toxapex',
    {
      abilities: { first: 'Merciless', second: 'Limber', hidden: 'Regenerator' },
      baseStats: { hp: 50, atk: 63, def: 152, spa: 53, spd: 142, spe: 35 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Blue',
      eggGroups: ['Water 1'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      evoLevel: 38,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.7,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 748,
      prevo: 'mareanie',
      species: 'toxapex',
      types: ['Poison', 'Water'],
      weightkg: 14.5,
      aliases: ['dohidoide', 'pex']
    }
  ],
  [
    'mudbray',
    {
      abilities: { first: 'Own Tempo', second: 'Stamina', hidden: 'Inner Focus' },
      baseStats: { hp: 70, atk: 100, def: 70, spa: 45, spd: 55, spe: 45 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['mudsdale'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 749,
      species: 'mudbray',
      types: ['Ground'],
      weightkg: 110,
      aliases: ['dorobanko']
    }
  ],
  [
    'mudsdale',
    {
      abilities: { first: 'Own Tempo', second: 'Stamina', hidden: 'Inner Focus' },
      baseStats: { hp: 100, atk: 125, def: 100, spa: 55, spd: 85, spe: 35 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Brown',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 30,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 750,
      prevo: 'mudbray',
      species: 'mudsdale',
      types: ['Ground'],
      weightkg: 920,
      aliases: ['banbadoro']
    }
  ],
  [
    'dewpider',
    {
      abilities: { first: 'Water Bubble', hidden: 'Water Absorb' },
      baseStats: { hp: 38, atk: 40, def: 52, spa: 40, spd: 72, spe: 27 },
      catchRate: {
        base: 200,
        percentageWithOrdinaryPokeballAtFullHealth: '36.6%'
      },
      color: 'Green',
      eggGroups: ['Water 1', 'Bug'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 1, spe: 0 },
      evos: ['araquanid'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 751,
      species: 'dewpider',
      types: ['Water', 'Bug'],
      weightkg: 4,
      aliases: ['shizukumo']
    }
  ],
  [
    'araquanid',
    {
      abilities: { first: 'Water Bubble', hidden: 'Water Absorb' },
      baseStats: { hp: 68, atk: 70, def: 92, spa: 50, spd: 132, spe: 42 },
      catchRate: {
        base: 100,
        percentageWithOrdinaryPokeballAtFullHealth: '21.7%'
      },
      color: 'Green',
      eggGroups: ['Water 1', 'Bug'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      evoLevel: 22,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.8,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 752,
      otherFormes: ['araquanidtotem'],
      prevo: 'dewpider',
      species: 'araquanid',
      types: ['Water', 'Bug'],
      weightkg: 82,
      aliases: ['onishizukumo']
    }
  ],
  [
    'araquanidtotem',
    {
      abilities: { first: 'Water Bubble' },
      baseSpecies: 'Araquanid',
      baseStats: { hp: 68, atk: 70, def: 92, spa: 50, spd: 132, spe: 42 },
      catchRate: {
        base: 100,
        percentageWithOrdinaryPokeballAtFullHealth: '21.7%'
      },
      color: 'Green',
      eggGroups: ['Water 1', 'Bug'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 3.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 752,
      species: 'araquanid-totem',
      types: ['Water', 'Bug'],
      weightkg: 217.5,
      aliases: ['araquanidt', 'totemaraquanid']
    }
  ],
  [
    'fomantis',
    {
      abilities: { first: 'Leaf Guard', hidden: 'Contrary' },
      baseStats: { hp: 40, atk: 55, def: 35, spa: 50, spd: 35, spe: 35 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Pink',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['lurantis'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 753,
      species: 'fomantis',
      types: ['Grass'],
      weightkg: 1.5,
      aliases: ['karikiri']
    }
  ],
  [
    'lurantis',
    {
      abilities: { first: 'Leaf Guard', hidden: 'Contrary' },
      baseStats: { hp: 70, atk: 105, def: 90, spa: 80, spd: 90, spe: 45 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Pink',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 34,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.9,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 754,
      otherFormes: ['lurantistotem'],
      prevo: 'fomantis',
      species: 'lurantis',
      types: ['Grass'],
      weightkg: 18.5,
      aliases: ['rarantesu']
    }
  ],
  [
    'lurantistotem',
    {
      abilities: { first: 'Leaf Guard' },
      baseSpecies: 'Lurantis',
      baseStats: { hp: 70, atk: 105, def: 90, spa: 80, spd: 90, spe: 45 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Pink',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 754,
      species: 'lurantis-totem',
      types: ['Grass'],
      weightkg: 58,
      aliases: ['lurantist', 'totemlurantis']
    }
  ],
  [
    'morelull',
    {
      abilities: {
        first: 'Illuminate',
        second: 'Effect Spore',
        hidden: 'Rain Dish'
      },
      baseStats: { hp: 40, atk: 35, def: 55, spa: 65, spd: 75, spe: 15 },
      catchRate: {
        base: 190,
        percentageWithOrdinaryPokeballAtFullHealth: '35.2%'
      },
      color: 'Purple',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 1, spe: 0 },
      evos: ['shiinotic'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 755,
      species: 'morelull',
      types: ['Grass', 'Fairy'],
      weightkg: 1.5,
      aliases: ['nemashu']
    }
  ],
  [
    'shiinotic',
    {
      abilities: {
        first: 'Illuminate',
        second: 'Effect Spore',
        hidden: 'Rain Dish'
      },
      baseStats: { hp: 60, atk: 45, def: 80, spa: 90, spd: 100, spe: 30 },
      catchRate: { base: 75, percentageWithOrdinaryPokeballAtFullHealth: '17.5%' },
      color: 'Purple',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      evoLevel: 24,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 756,
      prevo: 'morelull',
      species: 'shiinotic',
      types: ['Grass', 'Fairy'],
      weightkg: 11.5,
      aliases: ['masheedo']
    }
  ],
  [
    'salandit',
    {
      abilities: { first: 'Corrosion', hidden: 'Oblivious' },
      baseStats: { hp: 48, atk: 44, def: 40, spa: 71, spd: 40, spe: 77 },
      catchRate: {
        base: 120,
        percentageWithOrdinaryPokeballAtFullHealth: '24.9%'
      },
      color: 'Black',
      eggGroups: ['Monster', 'Dragon'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 1 },
      evos: ['salazzle'],
      genderRatio: { male: '87.5%', female: '12.5%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 757,
      species: 'salandit',
      types: ['Poison', 'Fire'],
      weightkg: 4.8,
      aliases: ['yatoumori']
    }
  ],
  [
    'salazzle',
    {
      abilities: { first: 'Corrosion', hidden: 'Oblivious' },
      baseStats: { hp: 68, atk: 64, def: 60, spa: 111, spd: 60, spe: 117 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Black',
      eggGroups: ['Monster', 'Dragon'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      evoLevel: 'Level 33, Female only',
      genderRatio: { male: '0%', female: '100%' },
      heightm: 1.2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 758,
      otherFormes: ['salazzletotem'],
      prevo: 'salandit',
      species: 'salazzle',
      types: ['Poison', 'Fire'],
      weightkg: 22.2,
      aliases: ['ennyuuto']
    }
  ],
  [
    'salazzletotem',
    {
      abilities: { first: 'Corrosion' },
      baseSpecies: 'Salazzle',
      baseStats: { hp: 68, atk: 64, def: 60, spa: 111, spd: 60, spe: 117 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Black',
      eggGroups: ['Monster', 'Dragon'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '0%', female: '100%' },
      heightm: 2.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 758,
      species: 'salazzle-totem',
      types: ['Poison', 'Fire'],
      weightkg: 81,
      aliases: ['salazzlet', 'totemsalazzle']
    }
  ],
  [
    'stufful',
    {
      abilities: { first: 'Fluffy', second: 'Klutz', hidden: 'Cute Charm' },
      baseStats: { hp: 70, atk: 75, def: 50, spa: 45, spd: 50, spe: 50 },
      catchRate: { base: 140, percentageWithOrdinaryPokeballAtFullHealth: '28%' },
      color: 'Pink',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['bewear'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 759,
      species: 'stufful',
      types: ['Normal', 'Fighting'],
      weightkg: 6.8,
      aliases: ['nuikoguma']
    }
  ],
  [
    'bewear',
    {
      abilities: { first: 'Fluffy', second: 'Klutz', hidden: 'Unnerve' },
      baseStats: { hp: 120, atk: 125, def: 80, spa: 55, spd: 60, spe: 60 },
      catchRate: { base: 70, percentageWithOrdinaryPokeballAtFullHealth: '16.6%' },
      color: 'Pink',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 27,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2.1,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 760,
      prevo: 'stufful',
      species: 'bewear',
      types: ['Normal', 'Fighting'],
      weightkg: 135,
      aliases: ['kiteruguma']
    }
  ],
  [
    'bounsweet',
    {
      abilities: {
        first: 'Leaf Guard',
        second: 'Oblivious',
        hidden: 'Sweet Veil'
      },
      baseStats: { hp: 42, atk: 30, def: 38, spa: 30, spd: 38, spe: 32 },
      catchRate: {
        base: 235,
        percentageWithOrdinaryPokeballAtFullHealth: '41.3%'
      },
      color: 'Purple',
      eggGroups: ['Grass'],
      evYields: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['steenee'],
      genderRatio: { male: '0%', female: '100%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 5140,
      num: 761,
      species: 'bounsweet',
      types: ['Grass'],
      weightkg: 3.2,
      aliases: ['amakaji']
    }
  ],
  [
    'steenee',
    {
      abilities: {
        first: 'Leaf Guard',
        second: 'Oblivious',
        hidden: 'Sweet Veil'
      },
      baseStats: { hp: 52, atk: 40, def: 48, spa: 40, spd: 48, spe: 62 },
      catchRate: {
        base: 120,
        percentageWithOrdinaryPokeballAtFullHealth: '24.9%'
      },
      color: 'Purple',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 2 },
      evoLevel: 18,
      evos: ['tsareena'],
      genderRatio: { male: '0%', female: '100%' },
      heightm: 0.7,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 5140,
      num: 762,
      prevo: 'bounsweet',
      species: 'steenee',
      types: ['Grass'],
      weightkg: 8.2,
      aliases: ['amamaiko']
    }
  ],
  [
    'tsareena',
    {
      abilities: {
        first: 'Leaf Guard',
        second: 'Queenly Majesty',
        hidden: 'Sweet Veil'
      },
      baseStats: { hp: 72, atk: 120, def: 98, spa: 50, spd: 98, spe: 72 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Purple',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'Level 19 while knowing Stomp',
      genderRatio: { male: '0%', female: '100%' },
      heightm: 1.2,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 5140,
      num: 763,
      prevo: 'steenee',
      species: 'tsareena',
      types: ['Grass'],
      weightkg: 21.4,
      aliases: ['amaajo']
    }
  ],
  [
    'comfey',
    {
      abilities: {
        first: 'Flower Veil',
        second: 'Triage',
        hidden: 'Natural Cure'
      },
      baseStats: { hp: 51, atk: 52, def: 90, spa: 82, spd: 110, spe: 100 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Green',
      eggGroups: ['Grass'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      genderRatio: { male: '25%', female: '75%' },
      heightm: 0.1,
      isEggObtainable: true,
      levellingRate: 'Fast',
      minimumHatchTime: 5140,
      num: 764,
      species: 'comfey',
      types: ['Fairy'],
      weightkg: 0.3,
      aliases: ['kyuwawaa']
    }
  ],
  [
    'oranguru',
    {
      abilities: {
        first: 'Inner Focus',
        second: 'Telepathy',
        hidden: 'Symbiosis'
      },
      baseStats: { hp: 90, atk: 60, def: 80, spa: 90, spd: 110, spe: 60 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.5,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 5140,
      num: 765,
      species: 'oranguru',
      types: ['Normal', 'Psychic'],
      weightkg: 76,
      aliases: ['yareyuutan']
    }
  ],
  [
    'passimian',
    {
      abilities: { first: 'Receiver', hidden: 'Defiant' },
      baseStats: { hp: 100, atk: 120, def: 90, spa: 40, spd: 60, spe: 80 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 5140,
      num: 766,
      species: 'passimian',
      types: ['Fighting'],
      weightkg: 82.8,
      aliases: ['nagetsukesaru']
    }
  ],
  [
    'wimpod',
    {
      abilities: { first: 'Wimp Out' },
      baseStats: { hp: 25, atk: 35, def: 40, spa: 20, spd: 30, spe: 80 },
      catchRate: { base: 90, percentageWithOrdinaryPokeballAtFullHealth: '20.1%' },
      color: 'Gray',
      eggGroups: ['Bug', 'Water 3'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 1 },
      evos: ['golisopod'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 767,
      species: 'wimpod',
      types: ['Bug', 'Water'],
      weightkg: 12,
      aliases: ['kosokumushi']
    }
  ],
  [
    'golisopod',
    {
      abilities: { first: 'Emergency Exit' },
      baseStats: { hp: 75, atk: 125, def: 140, spa: 60, spd: 90, spe: 40 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Gray',
      eggGroups: ['Bug', 'Water 3'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      evoLevel: 30,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 768,
      prevo: 'wimpod',
      species: 'golisopod',
      types: ['Bug', 'Water'],
      weightkg: 108,
      aliases: ['gusokumusha']
    }
  ],
  [
    'sandygast',
    {
      abilities: { first: 'Water Compaction', hidden: 'Sand Veil' },
      baseStats: { hp: 55, atk: 55, def: 80, spa: 70, spd: 45, spe: 15 },
      catchRate: { base: 140, percentageWithOrdinaryPokeballAtFullHealth: '28%' },
      color: 'Brown',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 1, spa: 0, spd: 0, spe: 0 },
      evos: ['palossand'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.5,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 769,
      species: 'sandygast',
      types: ['Ghost', 'Ground'],
      weightkg: 70,
      aliases: ['sunabaa']
    }
  ],
  [
    'palossand',
    {
      abilities: { first: 'Water Compaction', hidden: 'Sand Veil' },
      baseStats: { hp: 85, atk: 75, def: 110, spa: 100, spd: 75, spe: 35 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Brown',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      evoLevel: 42,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 770,
      prevo: 'sandygast',
      species: 'palossand',
      types: ['Ghost', 'Ground'],
      weightkg: 250,
      aliases: ['shirodesuna']
    }
  ],
  [
    'pyukumuku',
    {
      abilities: { first: 'Innards Out', hidden: 'Unaware' },
      baseStats: { hp: 55, atk: 60, def: 130, spa: 30, spd: 130, spe: 5 },
      catchRate: { base: 60, percentageWithOrdinaryPokeballAtFullHealth: '14.8%' },
      color: 'Black',
      eggGroups: ['Water 1'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Fast',
      minimumHatchTime: 3855,
      num: 771,
      species: 'pyukumuku',
      types: ['Water'],
      weightkg: 1.2,
      aliases: ['namakobushi', 'pyuku']
    }
  ],
  [
    'typenull',
    {
      abilities: { first: 'Battle Armor' },
      baseForme: 'Type: Null',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 59 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 2, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['silvally'],
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.9,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 772,
      species: 'Type: Null',
      types: ['Normal'],
      weightkg: 120.5,
      aliases: ['taipunuru', 'type null', 'type: null']
    }
  ],
  [
    'silvally',
    {
      abilities: { first: 'RKS System' },
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'Level up with happiness of at least 220',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      otherFormes: [
        'silvallybug',
        'silvallydark',
        'silvallydragon',
        'silvallyelectric',
        'silvallyfairy',
        'silvallyfighting',
        'silvallyfire',
        'silvallyflying',
        'silvallyghost',
        'silvallygrass',
        'silvallyground',
        'silvallyice',
        'silvallypoison',
        'silvallypsychic',
        'silvallyrock',
        'silvallysteel',
        'silvallywater'
      ],
      prevo: 'typenull',
      species: 'silvally',
      types: ['Normal'],
      weightkg: 100.5,
      aliases: ['shiruvuadi']
    }
  ],
  [
    'silvallybug',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Bug',
      formeLetter: 'B',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-bug',
      types: ['Bug'],
      weightkg: 100.5
    }
  ],
  [
    'silvallydark',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Dark',
      formeLetter: 'D',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-dark',
      types: ['Dark'],
      weightkg: 100.5
    }
  ],
  [
    'silvallydragon',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Dragon',
      formeLetter: 'D',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-dragon',
      types: ['Dragon'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyelectric',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Electric',
      formeLetter: 'E',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-electric',
      types: ['Electric'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyfairy',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Fairy',
      formeLetter: 'F',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-fairy',
      types: ['Fairy'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyfighting',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Fighting',
      formeLetter: 'F',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-fighting',
      types: ['Fighting'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyfire',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Fire',
      formeLetter: 'F',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-fire',
      types: ['Fire'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyflying',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Flying',
      formeLetter: 'F',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-flying',
      types: ['Flying'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyghost',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Ghost',
      formeLetter: 'G',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-ghost',
      types: ['Ghost'],
      weightkg: 100.5
    }
  ],
  [
    'silvallygrass',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Grass',
      formeLetter: 'G',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-grass',
      types: ['Grass'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyground',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Ground',
      formeLetter: 'G',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-ground',
      types: ['Ground'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyice',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Ice',
      formeLetter: 'I',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-ice',
      types: ['Ice'],
      weightkg: 100.5
    }
  ],
  [
    'silvallypoison',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Poison',
      formeLetter: 'P',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-poison',
      types: ['Poison'],
      weightkg: 100.5
    }
  ],
  [
    'silvallypsychic',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Psychic',
      formeLetter: 'P',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-psychic',
      types: ['Psychic'],
      weightkg: 100.5
    }
  ],
  [
    'silvallyrock',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Rock',
      formeLetter: 'R',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-rock',
      types: ['Rock'],
      weightkg: 100.5
    }
  ],
  [
    'silvallysteel',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Steel',
      formeLetter: 'S',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-steel',
      types: ['Steel'],
      weightkg: 100.5
    }
  ],
  [
    'silvallywater',
    {
      abilities: { first: 'RKS System' },
      baseSpecies: 'Silvally',
      baseStats: { hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 2,
      forme: 'Water',
      formeLetter: 'W',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 773,
      prevo: 'typenull',
      species: 'silvally-water',
      types: ['Water'],
      weightkg: 100.5
    }
  ],
  [
    'minior',
    {
      abilities: { first: 'Shields Down' },
      baseForme: 'Red',
      baseStats: { hp: 60, atk: 100, def: 60, spa: 100, spd: 60, spe: 120 },
      catchRate: { base: 30, percentageWithOrdinaryPokeballAtFullHealth: '8.8%' },
      color: 'Red',
      cosmeticFormes: ['Minior-Orange', 'Minior-Yellow', 'Minior-Green', 'Minior-Blue', 'Minior-Indigo', 'Minior-Violet'],
      eggGroups: ['Mineral'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 1, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 6425,
      num: 774,
      otherFormes: ['miniormeteor'],
      species: 'minior',
      types: ['Rock', 'Flying'],
      weightkg: 0.3,
      aliases: ['meteno', 'miniorblue', 'miniorgreen', 'miniorindigo', 'miniororange', 'miniorred', 'miniorviolet', 'minioryellow']
    }
  ],
  [
    'miniormeteor',
    {
      abilities: { first: 'Shields Down' },
      baseSpecies: 'Minior',
      baseStats: { hp: 60, atk: 60, def: 100, spa: 60, spd: 100, spe: 60 },
      catchRate: { base: 30, percentageWithOrdinaryPokeballAtFullHealth: '8.8%' },
      color: 'Brown',
      eggGroups: ['Mineral'],
      evYields: { hp: 0, atk: 0, def: 1, spa: 0, spd: 1, spe: 0 },
      forme: 'Meteor',
      formeLetter: 'M',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Slow',
      minimumHatchTime: 6425,
      num: 774,
      species: 'minior-meteor',
      types: ['Rock', 'Flying'],
      weightkg: 40
    }
  ],
  [
    'komala',
    {
      abilities: { first: 'Comatose' },
      baseStats: { hp: 65, atk: 115, def: 65, spa: 75, spd: 95, spe: 65 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Field'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 5140,
      num: 775,
      species: 'komala',
      types: ['Normal'],
      weightkg: 19.9,
      aliases: ['nekkoara']
    }
  ],
  [
    'turtonator',
    {
      abilities: { first: 'Shell Armor' },
      baseStats: { hp: 60, atk: 78, def: 135, spa: 91, spd: 85, spe: 36 },
      catchRate: { base: 70, percentageWithOrdinaryPokeballAtFullHealth: '16.6%' },
      color: 'Red',
      eggGroups: ['Monster', 'Dragon'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 776,
      species: 'turtonator',
      types: ['Fire', 'Dragon'],
      weightkg: 212,
      aliases: ['bakugamesu']
    }
  ],
  [
    'togedemaru',
    {
      abilities: {
        first: 'Iron Barbs',
        second: 'Lightning Rod',
        hidden: 'Sturdy'
      },
      baseStats: { hp: 65, atk: 98, def: 63, spa: 40, spd: 73, spe: 96 },
      catchRate: {
        base: 180,
        percentageWithOrdinaryPokeballAtFullHealth: '33.8%'
      },
      color: 'Gray',
      eggGroups: ['Field', 'Fairy'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 2570,
      num: 777,
      otherFormes: ['togedemarutotem'],
      species: 'togedemaru',
      types: ['Electric', 'Steel'],
      weightkg: 3.3
    }
  ],
  [
    'togedemarutotem',
    {
      abilities: { first: 'Sturdy' },
      baseSpecies: 'Togedemaru',
      baseStats: { hp: 65, atk: 98, def: 63, spa: 40, spd: 73, spe: 96 },
      catchRate: {
        base: 180,
        percentageWithOrdinaryPokeballAtFullHealth: '33.8%'
      },
      color: 'Gray',
      eggGroups: ['Field', 'Fairy'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 2570,
      num: 777,
      species: 'togedemaru-totem',
      types: ['Electric', 'Steel'],
      weightkg: 13
    }
  ],
  [
    'mimikyu',
    {
      abilities: { first: 'Disguise' },
      baseForme: 'Disguised',
      baseStats: { hp: 55, atk: 90, def: 80, spa: 50, spd: 105, spe: 96 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Yellow',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 778,
      otherFormes: ['mimikyubusted', 'mimikyutotem', 'mimikyubustedtotem'],
      species: 'mimikyu',
      types: ['Ghost', 'Fairy'],
      weightkg: 0.7,
      aliases: ['mimikkyu', 'mimikyudisguised']
    }
  ],
  [
    'mimikyubusted',
    {
      abilities: { first: 'Disguise' },
      baseSpecies: 'Mimikyu',
      baseStats: { hp: 55, atk: 90, def: 80, spa: 50, spd: 105, spe: 96 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Yellow',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      forme: 'Busted',
      formeLetter: 'B',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.2,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 778,
      species: 'mimikyu-busted',
      types: ['Ghost', 'Fairy'],
      weightkg: 0.7
    }
  ],
  [
    'mimikyutotem',
    {
      abilities: { first: 'Disguise' },
      baseSpecies: 'Mimikyu',
      baseStats: { hp: 55, atk: 90, def: 80, spa: 50, spd: 105, spe: 96 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Yellow',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 778,
      species: 'mimikyu-totem',
      types: ['Ghost', 'Fairy'],
      weightkg: 2.8,
      aliases: ['mimikyut', 'totemmimikyu']
    }
  ],
  [
    'mimikyubustedtotem',
    {
      abilities: { first: 'Disguise' },
      baseSpecies: 'Mimikyu',
      baseStats: { hp: 55, atk: 90, def: 80, spa: 50, spd: 105, spe: 96 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Yellow',
      eggGroups: ['Amorphous'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 2, spe: 0 },
      forme: 'Busted-Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.4,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 778,
      species: 'mimikyu-busted-totem',
      types: ['Ghost', 'Fairy'],
      weightkg: 2.8
    }
  ],
  [
    'bruxish',
    {
      abilities: {
        first: 'Dazzling',
        second: 'Strong Jaw',
        hidden: 'Wonder Skin'
      },
      baseStats: { hp: 68, atk: 105, def: 70, spa: 70, spd: 70, spe: 92 },
      catchRate: { base: 80, percentageWithOrdinaryPokeballAtFullHealth: '18.4%' },
      color: 'Pink',
      eggGroups: ['Water 2'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.9,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 3855,
      num: 779,
      species: 'bruxish',
      types: ['Water', 'Psychic'],
      weightkg: 19,
      aliases: ['hagigishiri']
    }
  ],
  [
    'drampa',
    {
      abilities: { first: 'Berserk', second: 'Sap Sipper', hidden: 'Cloud Nine' },
      baseStats: { hp: 78, atk: 60, def: 85, spa: 135, spd: 91, spe: 36 },
      catchRate: { base: 70, percentageWithOrdinaryPokeballAtFullHealth: '16.6%' },
      color: 'White',
      eggGroups: ['Monster', 'Dragon'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 2, spd: 0, spe: 0 },
      genderRatio: { male: '50%', female: '50%' },
      heightm: 3,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 5140,
      num: 780,
      species: 'drampa',
      types: ['Normal', 'Dragon'],
      weightkg: 185,
      aliases: ['jijiiron']
    }
  ],
  [
    'dhelmise',
    {
      abilities: { first: 'Steelworker' },
      baseStats: { hp: 70, atk: 131, def: 100, spa: 86, spd: 90, spe: 40 },
      catchRate: { base: 25, percentageWithOrdinaryPokeballAtFullHealth: '7.7%' },
      color: 'Green',
      eggGroups: ['Mineral'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 3.9,
      isEggObtainable: true,
      levellingRate: 'Medium Fast',
      minimumHatchTime: 6425,
      num: 781,
      species: 'dhelmise',
      types: ['Ghost', 'Grass'],
      weightkg: 210,
      aliases: ['dadarin']
    }
  ],
  [
    'jangmoo',
    {
      abilities: {
        first: 'Bulletproof',
        second: 'Soundproof',
        hidden: 'Overcoat'
      },
      baseStats: { hp: 45, atk: 55, def: 65, spa: 45, spd: 45, spe: 45 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Gray',
      eggGroups: ['Dragon'],
      evYields: { hp: 0, atk: 0, def: 1, spa: 0, spd: 0, spe: 0 },
      evos: ['hakamoo'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 0.6,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 10280,
      num: 782,
      specialBulbapediaUrl: 'Jangmo-o',
      species: 'jangmo-o',
      types: ['Dragon'],
      weightkg: 29.7,
      aliases: ['jarako']
    }
  ],
  [
    'hakamoo',
    {
      abilities: {
        first: 'Bulletproof',
        second: 'Soundproof',
        hidden: 'Overcoat'
      },
      baseStats: { hp: 55, atk: 75, def: 90, spa: 65, spd: 70, spe: 65 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Gray',
      eggGroups: ['Dragon'],
      evYields: { hp: 0, atk: 0, def: 2, spa: 0, spd: 0, spe: 0 },
      evoLevel: 35,
      evos: ['kommoo'],
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.2,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 10280,
      num: 783,
      prevo: 'jangmoo',
      specialBulbapediaUrl: 'Hakamo-o',
      species: 'hakamo-o',
      types: ['Dragon', 'Fighting'],
      weightkg: 47,
      aliases: ['jarango']
    }
  ],
  [
    'kommoo',
    {
      abilities: {
        first: 'Bulletproof',
        second: 'Soundproof',
        hidden: 'Overcoat'
      },
      baseStats: { hp: 75, atk: 110, def: 125, spa: 100, spd: 105, spe: 85 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Gray',
      eggGroups: ['Dragon'],
      evYields: { hp: 0, atk: 0, def: 3, spa: 0, spd: 0, spe: 0 },
      evoLevel: 45,
      genderRatio: { male: '50%', female: '50%' },
      heightm: 1.6,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 10280,
      num: 784,
      otherFormes: ['kommoototem'],
      prevo: 'hakamoo',
      specialBulbapediaUrl: 'Kommo-o',
      species: 'kommo-o',
      types: ['Dragon', 'Fighting'],
      weightkg: 78.2,
      aliases: ['clanger', 'jararanga']
    }
  ],
  [
    'kommoototem',
    {
      abilities: { first: 'Overcoat' },
      baseSpecies: 'Kommo-o',
      baseStats: { hp: 75, atk: 110, def: 125, spa: 100, spd: 105, spe: 85 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Gray',
      eggGroups: ['Dragon'],
      evYields: { hp: 0, atk: 0, def: 3, spa: 0, spd: 0, spe: 0 },
      forme: 'Totem',
      formeLetter: 'T',
      genderRatio: { male: '50%', female: '50%' },
      heightm: 2.4,
      isEggObtainable: true,
      levellingRate: 'Slow',
      minimumHatchTime: 10280,
      num: 784,
      species: 'kommo-o-totem',
      types: ['Dragon', 'Fighting'],
      weightkg: 207.5,
      aliases: ['kommoot', 'totemkommoo']
    }
  ],
  [
    'tapukoko',
    {
      abilities: { first: 'Electric Surge', hidden: 'Telepathy' },
      baseStats: { hp: 70, atk: 115, def: 85, spa: 95, spd: 75, spe: 130 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Yellow',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 3 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.8,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 3855,
      num: 785,
      species: 'Tapu Koko',
      types: ['Electric', 'Fairy'],
      weightkg: 20.5,
      aliases: ['kapukokeko', 'koko', 'tapu koko']
    }
  ],
  [
    'tapulele',
    {
      abilities: { first: 'Psychic Surge', hidden: 'Telepathy' },
      baseStats: { hp: 70, atk: 85, def: 75, spa: 130, spd: 115, spe: 95 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Pink',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 3855,
      num: 786,
      species: 'Tapu Lele',
      types: ['Psychic', 'Fairy'],
      weightkg: 18.6,
      aliases: ['kaputetefu', 'lele', 'tapu lele']
    }
  ],
  [
    'tapubulu',
    {
      abilities: { first: 'Grassy Surge', hidden: 'Telepathy' },
      baseStats: { hp: 70, atk: 130, def: 115, spa: 85, spd: 95, spe: 75 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Red',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.9,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 3855,
      num: 787,
      species: 'Tapu Bulu',
      types: ['Grass', 'Fairy'],
      weightkg: 45.5,
      aliases: ['bulu', 'kapubururu', 'tapu bulu']
    }
  ],
  [
    'tapufini',
    {
      abilities: { first: 'Misty Surge', hidden: 'Telepathy' },
      baseStats: { hp: 70, atk: 75, def: 115, spa: 95, spd: 130, spe: 85 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Purple',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 3, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 3855,
      num: 788,
      species: 'Tapu Fini',
      types: ['Water', 'Fairy'],
      weightkg: 21.2,
      aliases: ['fini', 'kapurehire', 'tapu fini']
    }
  ],
  [
    'cosmog',
    {
      abilities: { first: 'Unaware' },
      baseStats: { hp: 43, atk: 29, def: 31, spa: 29, spd: 31, spe: 37 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['cosmoem'],
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 789,
      species: 'cosmog',
      types: ['Psychic'],
      weightkg: 0.1,
      aliases: ['kosumoggu', 'mene', 'nebby']
    }
  ],
  [
    'cosmoem',
    {
      abilities: { first: 'Sturdy' },
      baseStats: { hp: 43, atk: 29, def: 131, spa: 29, spd: 131, spe: 37 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Blue',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 1, spa: 0, spd: 1, spe: 0 },
      evoLevel: 43,
      evos: ['solgaleo', 'lunala'],
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.1,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 790,
      prevo: 'cosmog',
      species: 'cosmoem',
      types: ['Psychic'],
      weightkg: 999.9,
      aliases: ['kosumoumu']
    }
  ],
  [
    'solgaleo',
    {
      abilities: { first: 'Full Metal Body' },
      baseStats: { hp: 137, atk: 137, def: 107, spa: 113, spd: 89, spe: 97 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 53,
      genderRatio: { male: '0%', female: '0%' },
      heightm: 3.4,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 791,
      prevo: 'cosmoem',
      species: 'solgaleo',
      types: ['Psychic', 'Steel'],
      weightkg: 230,
      aliases: ['sorugareo']
    }
  ],
  [
    'lunala',
    {
      abilities: { first: 'Shadow Shield' },
      baseStats: { hp: 137, atk: 113, def: 89, spa: 137, spd: 107, spe: 97 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Purple',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      evoLevel: 53,
      genderRatio: { male: '0%', female: '0%' },
      heightm: 4,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 792,
      prevo: 'cosmoem',
      species: 'lunala',
      types: ['Psychic', 'Ghost'],
      weightkg: 120,
      aliases: ['runaaara']
    }
  ],
  [
    'nihilego',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 109, atk: 53, def: 47, spa: 127, spd: 131, spe: 103 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 3, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 793,
      species: 'nihilego',
      types: ['Rock', 'Poison'],
      weightkg: 55.5,
      aliases: ['lego', 'ub01', 'utsuroido']
    }
  ],
  [
    'buzzwole',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 107, atk: 139, def: 139, spa: 53, spd: 53, spe: 79 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Red',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 1, def: 2, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.4,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 794,
      species: 'buzzwole',
      types: ['Bug', 'Fighting'],
      weightkg: 333.6,
      aliases: ['masshibuun', 'swole', 'ub02a']
    }
  ],
  [
    'pheromosa',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 71, atk: 137, def: 37, spa: 137, spd: 37, spe: 151 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 3 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.8,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 795,
      species: 'pheromosa',
      types: ['Bug', 'Fighting'],
      weightkg: 25,
      aliases: ['fierooche', 'phero', 'ub02b']
    }
  ],
  [
    'xurkitree',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 83, atk: 89, def: 71, spa: 173, spd: 71, spe: 83 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Black',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 3.8,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 796,
      species: 'xurkitree',
      types: ['Electric'],
      weightkg: 100,
      aliases: ['denjumoku', 'ub03', 'xurk']
    }
  ],
  [
    'celesteela',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 97, atk: 101, def: 103, spa: 107, spd: 101, spe: 61 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Green',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 1, def: 1, spa: 1, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 9.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 797,
      species: 'celesteela',
      types: ['Steel', 'Flying'],
      weightkg: 999.9,
      aliases: ['steela', 'tekkaguya', 'ub04blaster']
    }
  ],
  [
    'kartana',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 59, atk: 181, def: 131, spa: 59, spd: 31, spe: 109 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'White',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.3,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 798,
      species: 'kartana',
      types: ['Grass', 'Steel'],
      weightkg: 0.1,
      aliases: ['kamitsurugi', 'kart', 'ub04blade']
    }
  ],
  [
    'guzzlord',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 223, atk: 101, def: 53, spa: 97, spd: 53, spe: 43 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Black',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 3, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 5.5,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 799,
      species: 'guzzlord',
      types: ['Dark', 'Dragon'],
      weightkg: 888,
      aliases: ['akujikingu', 'ub05']
    }
  ],
  [
    'necrozma',
    {
      abilities: { first: 'Prism Armor' },
      baseStats: { hp: 97, atk: 107, def: 101, spa: 127, spd: 89, spe: 79 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Black',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 2, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.4,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 800,
      otherFormes: ['necrozmaduskmane', 'necrozmadawnwings', 'necrozmaultra'],
      species: 'necrozma',
      types: ['Psychic'],
      weightkg: 230,
      aliases: ['nekurozuma']
    }
  ],
  [
    'necrozmaduskmane',
    {
      abilities: { first: 'Prism Armor' },
      baseSpecies: 'Necrozma',
      baseStats: { hp: 97, atk: 157, def: 127, spa: 113, spd: 109, spe: 77 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Yellow',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'Dusk-Mane',
      formeLetter: 'D',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 3.8,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 800,
      species: 'necrozma-dusk-mane',
      types: ['Psychic', 'Steel'],
      weightkg: 460,
      aliases: [
        'duskmane',
        'duskmanenecrozma',
        'ndm',
        'necrozma dusk mane',
        'necrozma dusk',
        'necrozma-dusk-mane',
        'necrozma-dusk',
        'necrozmadm',
        'necrozmadusk'
      ]
    }
  ],
  [
    'necrozmadawnwings',
    {
      abilities: { first: 'Prism Armor' },
      baseSpecies: 'Necrozma',
      baseStats: { hp: 97, atk: 113, def: 109, spa: 157, spd: 127, spe: 77 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Blue',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      forme: 'Dawn-Wings',
      formeLetter: 'D',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 4.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 800,
      species: 'necrozma-dawn-wings',
      types: ['Psychic', 'Ghost'],
      weightkg: 350,
      aliases: [
        'dawnwings',
        'dawnwingsnecrozma',
        'ndw',
        'necrozma dawn wings',
        'necrozma dawn',
        'necrozma-dawn-wings',
        'necrozma-dawn',
        'necrozmadawn',
        'necrozmadw'
      ]
    }
  ],
  [
    'necrozmaultra',
    {
      abilities: { first: 'Neuroforce' },
      baseSpecies: 'Necrozma',
      baseStats: { hp: 97, atk: 167, def: 97, spa: 167, spd: 97, spe: 129 },
      catchRate: {
        base: 255,
        percentageWithOrdinaryPokeballAtFullHealth: '43.9%'
      },
      color: 'Blue',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 1, spd: 0, spe: 1 },
      forme: 'Ultra',
      formeLetter: 'U',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 7.5,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 800,
      species: 'necrozma-ultra',
      types: ['Psychic', 'Dragon'],
      weightkg: 230,
      aliases: ['necrozmau', 'ultranecrozma', 'unecro']
    }
  ],
  [
    'magearna',
    {
      abilities: { first: 'Soul-Heart' },
      baseStats: { hp: 80, atk: 95, def: 115, spa: 130, spd: 115, spe: 65 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 801,
      otherFormes: ['magearnaoriginal'],
      species: 'magearna',
      types: ['Steel', 'Fairy'],
      weightkg: 80.5,
      aliases: ['mage', 'magiana']
    }
  ],
  [
    'magearnaoriginal',
    {
      abilities: { first: 'Soul-Heart' },
      baseSpecies: 'Magearna',
      baseStats: { hp: 80, atk: 95, def: 115, spa: 130, spd: 115, spe: 65 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Red',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      forme: 'Original',
      formeLetter: 'O',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 801,
      species: 'magearna-original',
      types: ['Steel', 'Fairy'],
      weightkg: 80.5
    }
  ],
  [
    'marshadow',
    {
      abilities: { first: 'Technician' },
      baseStats: { hp: 90, atk: 125, def: 80, spa: 90, spd: 90, spe: 125 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 2, def: 0, spa: 0, spd: 0, spe: 1 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.7,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 802,
      species: 'marshadow',
      types: ['Fighting', 'Ghost'],
      weightkg: 22.2,
      aliases: ['maashadoo']
    }
  ],
  [
    'poipole',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 67, atk: 73, def: 67, spa: 73, spd: 67, spe: 73 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Purple',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 1 },
      evos: ['naganadel'],
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.6,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 803,
      species: 'poipole',
      types: ['Poison'],
      weightkg: 1.8,
      aliases: ['bebenomu', 'ubadhesive']
    }
  ],
  [
    'naganadel',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 73, atk: 73, def: 73, spa: 127, spd: 73, spe: 121 },
      catchRate: { base: 45, percentageWithOrdinaryPokeballAtFullHealth: '11.9%' },
      color: 'Purple',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      evoLevel: 41,
      genderRatio: { male: '0%', female: '0%' },
      heightm: 3.6,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 804,
      prevo: 'poipole',
      species: 'naganadel',
      types: ['Poison', 'Dragon'],
      weightkg: 150,
      aliases: ['aagoyon', 'naga']
    }
  ],
  [
    'stakataka',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 61, atk: 131, def: 211, spa: 53, spd: 101, spe: 13 },
      catchRate: { base: 30, percentageWithOrdinaryPokeballAtFullHealth: '8.8%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 3, spa: 0, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 5.5,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 805,
      species: 'stakataka',
      types: ['Rock', 'Steel'],
      weightkg: 820,
      aliases: ['staka', 'tsundetsunde', 'ubassembly']
    }
  ],
  [
    'blacephalon',
    {
      abilities: { first: 'Beast Boost' },
      baseStats: { hp: 53, atk: 127, def: 53, spa: 151, spd: 79, spe: 107 },
      catchRate: { base: 30, percentageWithOrdinaryPokeballAtFullHealth: '8.8%' },
      color: 'White',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 3, spd: 0, spe: 0 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.8,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 806,
      species: 'blacephalon',
      types: ['Fire', 'Ghost'],
      weightkg: 13,
      aliases: ['blace', 'ubburst', 'zugadoon']
    }
  ],
  [
    'zeraora',
    {
      abilities: { first: 'Volt Absorb' },
      baseStats: { hp: 88, atk: 112, def: 75, spa: 102, spd: 80, spe: 143 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Yellow',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 3 },
      genderRatio: { male: '0%', female: '0%' },
      heightm: 1.5,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 807,
      species: 'zeraora',
      types: ['Electric'],
      weightkg: 44.5
    }
  ],
  [
    'meltan',
    {
      abilities: { first: 'Magnet Pull' },
      baseStats: { hp: 46, atk: 65, def: 65, spa: 55, spd: 35, spe: 34 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 1, def: 0, spa: 0, spd: 0, spe: 0 },
      evos: ['melmetal'],
      genderRatio: { male: '0%', female: '0%' },
      heightm: 0.2,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 808,
      species: 'meltan',
      types: ['Steel'],
      weightkg: 8,
      aliases: ['merutan']
    }
  ],
  [
    'melmetal',
    {
      abilities: { first: 'Iron Fist' },
      baseStats: { hp: 135, atk: 143, def: 143, spa: 80, spd: 65, spe: 34 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      evoLevel: 'feed 400 Meltan Candy in Pokémon GO',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 2.5,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 809,
      otherFormes: ['melmetalgmax'],
      prevo: 'meltan',
      species: 'melmetal',
      types: ['Steel'],
      weightkg: 800,
      aliases: ['merumetaru']
    }
  ],
  [
    'melmetalgmax',
    {
      abilities: { first: 'Iron Fist' },
      baseSpecies: 'Melmetal',
      baseStats: { hp: 135, atk: 143, def: 143, spa: 80, spd: 65, spe: 34 },
      catchRate: { base: 3, percentageWithOrdinaryPokeballAtFullHealth: '1.6%' },
      color: 'Gray',
      eggGroups: ['Undiscovered'],
      evYields: { hp: 0, atk: 3, def: 0, spa: 0, spd: 0, spe: 0 },
      forme: 'Gmax',
      formeLetter: 'G',
      genderRatio: { male: '0%', female: '0%' },
      heightm: 20,
      isEggObtainable: false,
      levellingRate: 'Slow',
      minimumHatchTime: 30840,
      num: 809,
      species: 'melmetal-gmax',
      types: ['Steel'],
      weightkg: 1000,
      aliases: ['gigantamax melmetal']
    }
  ]
];

for (const [name, data] of entries) {
  Pokedex.set(name, data);
}
