export function getTextContent(bit1: string) {
  return bit1
    ?.split(/\|[a-z]+=/g)
    ?.at(-1)
    .replace(/}}$/, '')
    .replace(/{{p\|([a-zA-Z]+)}}/g, '$1')
    .replace(/{{p\|[a-zA-Z]+\|(evolve)}}/g, '$1')
    .replace(/{{m\|([a-zA-Z]+)}}/g, '$1')
    .replace(/{{tt\|([-a-zA-Z0-9, ]+)\|[-a-zA-Z0-9,\/ ]+}}/g, '$1')
    .replace(/{{a\|[-a-zA-Z0-9, ]+\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replaceAll('’', "'")
    .replaceAll('“', '"')
    .replaceAll('”', '"')
    .replaceAll('{{tt|*|Unused entry}}', '')
    .replaceAll('[[evolution]]', 'evolution')
    .replaceAll('[[Evolution|evolve]]', 'evolve')
    .replaceAll('[[Moon Stone|moon stone]]', 'moon stone')
    .replaceAll('[[regional form]]', 'regional form')
    .replaceAll('[[Pokégear]]', 'Pokégear')
    .replaceAll('[[alien]]', 'alien')
    .replaceAll('[[Double Slap (move)|DoubleSlap]]', 'DoubleSlap')
    .replaceAll('[[Old Amber|amber]]', 'amber')
    .replaceAll('[[Mr. Fuji|a certain scientist]]', 'a certain scientist')
    .replaceAll('[[move]]', 'move')
    .replaceAll('[[Berry|Berries]]', 'Berries')
    .replaceAll('[[Evolution|becomes]]', 'becomes')
    .replaceAll('[[Pupitar (Pokémon)|a pupa]]', 'a pupa')
    .replaceAll('[[Poké Ball]]', 'Poké Ball')
    .replaceAll('[[Gladion|the boy who evolved it into this form]]', 'the boy who evolved it into this form')
    .replaceAll('[[Ultra Beast]]', 'Ultra Beast')
    .replaceAll('[[Dynamax]]', 'Dynamax')
    .replaceAll('[[region]]', 'region')
    .replaceAll('[[Alola]]', 'Alola')
    .replaceAll('[[Hisui]]', 'Hisui')
    .replaceAll('[[Galar]]', 'Galar')
    .replaceAll('[[Paldea]]', 'Paldea')
    .replaceAll('[[Kitakami|a new land]]', 'a new land')
    .replaceAll('[[Scarlet Book|an expedition journal]]', 'an expedition journal')
    .replaceAll('[[Mega Evolution|a phenomenon that occurs in a certain region]]', 'a phenomenon that occurs in a certain region')
    .replaceAll('[[Violet Book|certain expedition journal.]]', 'certain expedition journal.')
    .replaceAll('[[Scarlet Book|old expedition journal]]', 'old expedition journal.')
    .replaceAll('[[Violet Book|old book]]', 'old book.');
}
