export function getTextContent(bit1: string) {
  return bit1
    ?.split(/\|[a-z]+=/g)
    ?.at(-1)
    .replace(/}}$/, '')
    .replace(/\s?<small>.+<\/small>/, '')
    .replaceAll(/<sc>([a-zA-Z0-9 {}|'.-]+)<\/sc>/g, '$1')
    .replaceAll(/{{[pP]\|([a-zA-Z']+)}}/g, '$1')
    .replaceAll(/{{[pP]\|[a-zA-Z']+\|([a-zA-Z'é ]+)}}/g, '$1')
    .replaceAll(/{{p\|[a-zA-Z]+\|(evolve)}}/g, '$1')
    .replaceAll(/{{m\|([a-zA-Z ]+)}}/g, '$1')
    .replaceAll(/{{m\|[a-zA-Z ]+\|([a-zA-Z -]+)}}/g, '$1')
    .replaceAll(/{{t\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{tt\|([-a-zA-Z0-9,.\/()&;–−'"° ]+)\|[-a-zA-Z0-9,.\/()&;–−'"° ]+}}/g, '$1')
    .replaceAll(/{{a\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replaceAll(/{{a\|[-a-zA-Z0-9, ]+\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replaceAll(/{{status\|[-a-zA-Z0-9,.\/ ]+\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replaceAll(/{{status\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replaceAll(/{{pkmn\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{pkmn2\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{wp\|([a-zA-Z ]+)}}/g, '$1')
    .replaceAll(/{{wp\|[a-zA-Z ()]+\|([a-zA-Z. ]+)}}/g, '$1')
    .replace(/'''Version 1\.0:''' .+1.2:''' (.+)/, '$1')
    .replace(/'''Version 1\.0:''' .+1\.1:''' (.+)/, '$1')
    .replace(/'''Version 1\.0:''' .+1\.2:''' (.+)/, '$1')
    .replaceAll('{{tt|*|Pokédex entry only found in Pokémon HOME.}}', '')
    .replaceAll('{{tt|*|Pokédex entry only found in Pokémon HOME}}', '')
    .replaceAll('{{tt|*|In Ver 1.0, Tyranitar uses its entry from LeafGreen}}', '')
    .replaceAll('{{tt|*|Used for both genders in-game}}', '')
    .replaceAll('}}\t', '')
    .replaceAll('’', "'")
    .replaceAll('−', '-')
    .replaceAll('“', '"')
    .replaceAll('”', '"')
    .replaceAll(' <!--error in game--> ', ' ')
    .replaceAll('<!-- period is missing -->', '.')
    .replaceAll(`{{tt|–75<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−60 degrees Celsius}}`, '-75 degrees Fahrenheit')
    .replaceAll(`{{tt|–75<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-60 degrees Celsius}}`, '-75 degrees Fahrenheit')
    .replaceAll(`{{tt|–58<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−50 degrees Celsius}}`, '-58 degrees Fahrenheit')
    .replaceAll(`{{tt|–58<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-50 degrees Celsius}}`, '-58 degrees Fahrenheit')
    .replaceAll(`{{tt|–240<!--U+2013 EN DASH in-game--> degrees Fahrenheit|−150 degrees Celsius}}`, '-240 degrees Fahrenheit')
    .replaceAll(`{{tt|–240<!--U+2013 EN DASH in-game--> degrees Fahrenheit|-150 degrees Celsius}}`, '-240 degrees Fahrenheit')
    .replaceAll(`{{tt|this|''the'' in Ruby v1.0}}`, 'this')
    .replaceAll(`{{tt|Bug/Grass Pokémon|''BUG POKéMON'' in R/S v1.0}}`, 'Bug/Grass Pokémon')
    .replaceAll('{{tt|*|Unused entry}}', '')
    .replaceAll('[[alien]]', 'alien')
    .replaceAll('[[Alola]]', 'Alola')
    .replaceAll('[[Apricorn]]', 'Apricorn')
    .replaceAll('[[Berry|Berries]]', 'Berries')
    .replaceAll('[[Black Augurite|extremely rare ore]]', 'extremely rare ore')
    .replaceAll('[[Diamond Domain|kingdom of jewels]]', 'kingdom of jewels')
    .replaceAll('[[Distortion World|world]]', 'world')
    .replaceAll('[[Double Slap (move)|DoubleSlap]]', 'DoubleSlap')
    .replaceAll('[[Dynamax]]', 'Dynamax')
    .replaceAll('[[evolution]]', 'evolution')
    .replaceAll('[[Evolution|becomes]]', 'becomes')
    .replaceAll('[[Evolution|evolve]]', 'evolve')
    .replaceAll('[[Evolution|evolved]]', 'evolved')
    .replaceAll('[[Galar]]', 'Galar')
    .replaceAll('[[Galar|homeland]]', 'homeland')
    .replaceAll('[[Gladion|boy]]', 'boy')
    .replaceAll('[[Gladion|the boy who evolved it into this form]]', 'the boy who evolved it into this form')
    .replaceAll('[[Hisui]]', 'Hisui')
    .replaceAll('[[Hisui|much harsher environments]]', 'much harsher environments')
    .replaceAll('[[Kitakami|a new land]]', 'a new land')
    .replaceAll('[[legendary Pokémon]]', 'legendary Pokémon')
    .replaceAll('[[Mega Evolution|a phenomenon that occurs in a certain region]]', 'a phenomenon that occurs in a certain region')
    .replaceAll('[[Moon Stone|moon stone]]', 'moon stone')
    .replaceAll('[[move]]', 'move')
    .replaceAll('[[Mr. Fuji|a certain scientist]]', 'a certain scientist')
    .replaceAll('[[Old Amber|amber]]', 'amber')
    .replaceAll('[[Paldea]]', 'Paldea')
    .replaceAll('[[Poké Ball]]', 'Poké Ball')
    .replaceAll('[[Pokégear]]', 'Pokégear')
    .replaceAll('[[Pokégear|Pokégear]]', 'Pokégear')
    .replaceAll('[[Pokégear|é<sc>gear</sc>]]', 'Pokégear')
    .replaceAll('[[Pokégear|Poké<sc>gear</sc>]]', 'Pokégear')
    .replaceAll('[[Pokémon Trainer|Trainer]]', 'Trainer')
    .replaceAll('[[Pokémon world|ours]]', 'ours')
    .replaceAll('[[Professor Laventon|my]]', 'my')
    .replaceAll('[[Pupitar (Pokémon)|a pupa]]', 'a pupa')
    .replaceAll('[[region]]', 'region')
    .replaceAll('[[regional form]]', 'regional form')
    .replaceAll('[[Scarlet Book|an expedition journal]]', 'an expedition journal')
    .replaceAll('[[Scarlet Book|old expedition journal]]', 'old expedition journal.')
    .replaceAll('[[Sinnoh myths|mythology]]', 'mythology')
    .replaceAll('[[Sinnoh myths|myths]]', 'myths')
    .replaceAll('[[Sinnoh]]', 'Sinnoh')
    .replaceAll('[[Time travel|travel at will through the past and future]]', 'travel at will through the past and future')
    .replaceAll('[[type]]', 'type')
    .replaceAll('[[Ultra Beast]]', 'Ultra Beast')
    .replaceAll('[[Violet Book|certain expedition journal.]]', 'certain expedition journal.')
    .replaceAll('[[Violet Book|old book]]', 'old book')
    .replaceAll('{{OBP|Pokémon|species}}', 'Pokémon')
    .replaceAll('{{p|Type: Null}}', 'Type: Null')
    .replaceAll('{{ScBall}}', 'Poké Ball')
    .replaceAll('{{ScPkmn}}', 'Pokémon')
    .replaceAll('{{sup/4|HG}}/Froslass{{sup/4|SS}}', '')
    .replaceAll('lower-back{{sup/4|HG}}/lower back{{sup/4|SS}}', 'lower-back')
    .replaceAll('the{{sup/3|R}}/this{{sup/3|S}}', 'this')
    .replaceAll('a <!--typo exists in-game--> ', '')
    .replaceAll('<sc>Berries</sc>', 'Berries')
    .replaceAll("[[Dimension#Palkia's world|spatial dimension]]", 'spatial dimension');
}
