export function getTextContent(bit1: string) {
  return bit1
    ?.split(/\|[a-z]+=/g)
    ?.at(-1)
    .replace(/}}$/, '')
    .replace(/\s?<small>.+<\/small>/, '')
    .replaceAll(/<sc>([a-zA-Z0-9 {}|'.-]+)<\/sc>/g, '$1')
    .replaceAll(/{{[pP]\|([a-zA-Z']+)}}/g, '$1')
    .replaceAll(/{{[pP]\|[a-zA-Z']+\|([a-zA-Z'é ]+)}}/g, '$1')
    .replaceAll(/{{p\|[a-zA-Z]+\|(evolve)}}/g, '$1')
    .replaceAll(/{{m\|([a-zA-Z ]+)}}/g, '$1')
    .replaceAll(/{{m\|[a-zA-Z ]+\|([a-zA-Z -]+)}}/g, '$1')
    .replaceAll(/{{t\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{tt\|([-a-zA-Z0-9,.\/()&;–−'"° ]+)\|[-a-zA-Z0-9,.\/()&;–−'"° ]+}}/g, '$1')
    .replaceAll(/{{a\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replaceAll(/{{a\|[-a-zA-Z0-9, ]+\|([-a-zA-Z0-9,\/ ]+)}}/g, '$1')
    .replaceAll(/{{status\|[-a-zA-Z0-9,.\/ ]+\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replaceAll(/{{status\|([-a-zA-Z0-9,.\/ ]+)}}/g, '$1')
    .replaceAll(/{{pkmn\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{pkmn2\|([a-zA-Z]+)}}/g, '$1')
    .replaceAll(/{{wp\|([a-zA-Z ]+)}}/g, '$1')
    .replaceAll(/{{wp\|[a-zA-Z ()]+\|([a-zA-Z. ]+)}}/g, '$1')
    .replace(/'''Version 1\.0:''' .+1.2:''' (.+)/, '$1')
    .replace(/'''Version 1\.0:''' .+1\.1:''' (.+)/, '$1')
    .replace(/'''Version 1\.0:''' .+1\.2:''' (.+)/, '$1')
    .replaceAll(/\{\{tt\|\*\|(?:[\p{Letter}\d\p{Punctuation}\s]+?)\}\}/gu, '')
    .replaceAll('}}\t', '')
    .replaceAll('’', "'")
    .replaceAll('−', '-')
    .replaceAll('“', '"')
    .replaceAll('”', '"')
    .replaceAll(' <!--error in game--> ', ' ')
    .replaceAll('<!-- period is missing -->', '.')
    .replaceAll(/\{\{tt\|–(\d+)<!--U\+2013 EN DASH in-game--> degrees Fahrenheit\|(?:-|−)\d+ degrees Celsius\}\}/g, '-$1 degrees Fahrenheit')
    .replaceAll(`{{tt|this|''the'' in Ruby v1.0}}`, 'this')
    .replaceAll(`{{tt|Bug/Grass Pokémon|''BUG POKéMON'' in R/S v1.0}}`, 'Bug/Grass Pokémon')
    .replaceAll(
      /(?:\[\[(?<pokegearContent>Pokégear)(?:\|[\p{Letter}\p{Other_Punctuation}\s()<>]+)?\]\])|(?:\[\[(?:[\p{Letter}\p{Other_Punctuation}\s()<>]+\|)?(?<generalContent>[\p{Letter}\p{Other_Punctuation}\s()<>]+)\]\])/gu,
      '$<pokegearContent>$<generalContent>'
    )
    .replaceAll('{{OBP|Pokémon|species}}', 'Pokémon')
    .replaceAll('{{p|Type: Null}}', 'Type: Null')
    .replaceAll('{{ScBall}}', 'Poké Ball')
    .replaceAll('{{ScPkmn}}', 'Pokémon')
    .replaceAll('{{sup/4|HG}}/Froslass{{sup/4|SS}}', '')
    .replaceAll('lower-back{{sup/4|HG}}/lower back{{sup/4|SS}}', 'lower-back')
    .replaceAll('the{{sup/3|R}}/this{{sup/3|S}}', 'this')
    .replaceAll('a <!--typo exists in-game--> ', '')
    .replaceAll('<sc>Berries</sc>', 'Berries');
}
