import type { MiddlewareOptions } from '@apollographql/graphql-playground-html';

const isDev = process.env.NODE_ENV !== 'production';

const defaultTabs: NonNullable<MiddlewareOptions['tabs']> = [
  {
    name: 'Get Pokémon Details simple',
    endpoint: isDev ? `http://localhost:${process.env.PORT || 4000}` : 'https://graphqlpokemon.favware.tech/',
    query: [
      '{',
      '\tgetPokemon(pokemon: dragonite reverseFlavorTexts: true takeFlavorTexts: 1) {',
      '\t\tnum',
      '\t\tspecies',
      '\t\ttypes',
      '\t\tabilities { first second hidden }',
      '\t\tbaseStats { hp attack defense specialattack specialdefense speed }',
      '\t\tgender { male female }',
      '\t\theight',
      '\t\tweight',
      '\t\tflavorTexts { game flavor }',
      '\t\tevYields { hp attack defense specialattack specialdefense speed }',
      '\t\tisEggObtainable',
      '\t\tminimumHatchTime',
      '\t\tmaximumHatchTime',
      '\t\tlevellingRate',
      '\t\tsprite',
      '\t\tshinySprite',
      '\t\tbackSprite',
      '\t\tshinyBackSprite',
      '\t\tsmogonTier',
      '\t\tsmogonPage',
      '\t\tserebiiPage',
      '\t\tbulbapediaPage',
      '\t}',
      '}'
    ].join('\n')
  },
  {
    name: 'Pokémon Details with variables',
    endpoint: isDev ? `http://localhost:${process.env.PORT || 4000}` : 'https://graphqlpokemon.favware.tech/',
    variables: ['{', '  "pokemon": "mewtwo"', '}'].join('\n'),
    query: [
      'query($pokemon: PokemonEnum!) {',
      '\tgetPokemon(pokemon: $pokemon reverseFlavorTexts: true takeFlavorTexts: 1) {',
      '\t\tnum',
      '\t\tspecies',
      '\t\ttypes',
      '\t\tabilities { first second hidden }',
      '\t\tbaseStats { hp attack defense specialattack specialdefense speed }',
      '\t\tgender { male female }',
      '\t\theight',
      '\t\tweight',
      '\t\tflavorTexts { game flavor }',
      '\t\tevYields { hp attack defense specialattack specialdefense speed }',
      '\t\tisEggObtainable',
      '\t\tminimumHatchTime',
      '\t\tmaximumHatchTime',
      '\t\tlevellingRate',
      '\t\tsprite',
      '\t\tshinySprite',
      '\t\tbackSprite',
      '\t\tshinyBackSprite',
      '\t\tsmogonTier',
      '\t\tsmogonPage',
      '\t\tserebiiPage',
      '\t\tbulbapediaPage',
      '\t}',
      '}'
    ].join('\n')
  },
  {
    name: 'Pokémon Details with fragments and variables',
    endpoint: isDev ? `http://localhost:${process.env.PORT || 4000}` : 'https://graphqlpokemon.favware.tech/',
    variables: ['{', '  "pokemon": "arceus",', '  "reverse": true,', '  "take": 1', '}'].join('\n'),
    query: [
      'fragment data on Pokemon {',
      '\t\tnum',
      '\t\tspecies',
      '\t\ttypes',
      '\t\tabilities { first second hidden }',
      '\t\tbaseStats { hp attack defense specialattack specialdefense speed }',
      '\t\tgender { male female }',
      '\t\theight',
      '\t\tweight',
      '\t\tflavorTexts { game flavor }',
      '\t\tevYields { hp attack defense specialattack specialdefense speed }',
      '\t\tisEggObtainable',
      '\t\tminimumHatchTime',
      '\t\tmaximumHatchTime',
      '\t\tlevellingRate',
      '\t\tsprite',
      '\t\tshinySprite',
      '\t\tbackSprite',
      '\t\tshinyBackSprite',
      '\t\tsmogonTier',
      '\t\tsmogonPage',
      '\t\tserebiiPage',
      '\t\tbulbapediaPage',
      '}',
      '',
      'query($pokemon: PokemonEnum! $reverse: Boolean! $take: Int!) {',
      '\tgetPokemon(pokemon: $pokemon reverseFlavorTexts: $reverse takeFlavorTexts: $take) {',
      '\t\t...data',
      '\t}',
      '}'
    ].join('\n')
  }
];

export default defaultTabs;
